### ISSUE TITLE
Add Hazelcast chart as optional dependency in requirements yaml

### ISSUE THREAD

**Issue by salaboy** [zeebe-io/zeebe-zeeqs-helm#1]
@pocorschi it might be good to have an optional dependency in this chart.. in the same way that we have elasticsearch,  kibana and prometheus in the zeebe-cluster chart. So we don't actually need to install Hazelcast manually as a separate chart. 

https://github.com/zeebe-io/zeebe-cluster-helm/blob/master/zeebe-cluster/requirements.yaml#L2

Maybe you can send a PR for that as well.

**Comment by pocorschi** [comment]
@salaboy I think the optional dependency should be in [zeebe-cluster-helm](https://github.com/zeebe-io/zeebe-cluster-helm). The flow to install these should be zeebe-cluster -> zeeqs anyway no?
I'm thinking that ZeeQS should connect to an already existing hazelcast cluster, whether it's deployed by zeebe-cluster-helm or already existing on the user's K8S cluster, but introducing the option to add an additional hazelcast cluster here might be confusing. Let me know what you think.

**Comment by salaboy** [comment]
@pocorschi I get your point but in general, we should try to design all these charts and components to not depend on order. 
If we add more to` zeebe-cluster`, we might concentrate all the changes in a single place, make it more difficult to evolve. 
I would give it a try to adding it here, as ZeeQS really depends on hazelcast to work, @saig0  what do you think? how do you feel about my suggestion?

**Comment by pocorschi** [comment]
@salaboy  I understand what you mean and I have no problem giving it a shot. But the reasoning was that ZeeQS would always be installed after zeebe-cluster not the other way around. So the hazelcast cluster should be available for the hazelcast-exporter. 
But I will defer to your expertise. And if you decide so I can add the dependency here.

**Comment by saig0** [comment]
@salaboy, I'm not sure. For me, the Hazelcast cluster should be defined where the Hazelcast exporter is defined. The exporter is the producer of the data and multiple applications, like ZeeQS, consume from it. Also, the configuration of the exporter decides if the Hazelcast cluster is created in-memory or if it exports to an existing cluster.

**Comment by salaboy** [comment]
@saig0 let's think about it as dependencies more than where the data is originated. 
ZeeQS require a Hazelcast instance to work, the same as the exporter. Both should support configuration to point to the hazelcast instance that the user wants to use. 
From the ZeeQS chart perspective, we can offer the helper of an optional dependency to the chart to automatically provision a hazelcast instance. 
When I evaluate it from the "exporter" perspective, that is more complex, as the exporter is not a component that can run on its own. 
I think that we will make a mistake if we define how these components are connected together based on where the data is originated (producer/consumer) as we should make sure that the order in which these components are deployed doesn't affect their way of working. To put an example, as soon as the exporter and ZeeQS can find a hazelcast instance, it really doesn't matter who provision it. 
I hope that this makes sense.

**Comment by pocorschi** [comment]
@salaboy  - I added and tested adding the hazelcast external dependency in the requirements and it seems to be working fine. I will be opening a PR but I suggest merging that after @saig0  releases the new version of the hazelcast-exporter with the dependencies bumped to 4.0 for hazelcast in order to not force people to downgrade to an older version. What do you think?

**Comment by pocorschi** [comment]
Also as an added question, should we enable the dependency by default or should it be off and allow the user to choose if they need/want it ?

**Comment by salaboy** [comment]
@saig0 can you give us an update about the upgrade to hazelcast 4.0? 
@pocorschi it definitely needs to be optional.. the `default` value can be discussed, but I would leave it to `true`. What do you think?

**Comment by pocorschi** [comment]
I guess it depends on the starting assumption. If the user is installing Hazelcast specifically because of the tie-in to Zeebe or not. But since ZeeQS cannot work without a Hazelcast instance, and Elasticsearch is `true` by default in `zeebe-cluster-helm`, I would have it set to `true`.

**Comment by salaboy** [comment]
@pocorschi I totally agree with that.. let's have it true by default.

**Comment by saig0** [comment]
@salaboy, regarding the upgrade to Hazelcast 4. I want to make a coordinated release with all components that consume from Hazelcast to avoid incompatible versions. It is planned for this or next week.

**Comment by salaboy** [comment]
@saig0 perfect! let us know when that happens!

**Comment by saig0** [comment]
@salaboy, I released the projects. Now, they are running with Hazelcast `4.0.1`.

https://github.com/zeebe-io/zeebe-hazelcast-exporter/releases/tag/0.9.0
https://github.com/zeebe-io/zeeqs/releases/tag/1.0.0-alpha2

**Comment by salaboy** [comment]
yey! should we update the helm charts? to latest version?

**Comment by pocorschi** [comment]
@salaboy  - Updated the helm charts. Hazelcast is installed as external dependency and true by default. Just tested it with a fresh install of zeebe-cluster-helm (configured with hazelcast exporter) and it works 
Re: zeebe-cluster-helm. I've had issues configuring the exporter via ZeebeCfg and instead resorted to using ENVVARS. Also the README is outdated it seems using the old ( <23.x) way of configuring exporter. I'll open an issue and a  PR with an updated README and I would suggest adding a sample values.yaml with a hazelcast exporter configuration. What do you think about that?

**Comment by salaboy** [comment]
@pocorschi can you please send a PR to the chart as well.. so I can test it on my side?

**Comment by salaboy** [comment]
@pocorschi where did you updated the helm chart -> "Updated the helm charts? "

**Comment by pocorschi** [comment]
@salaboy - #2 here

**Comment by pocorschi** [comment]
@salaboy  - i saw that you merged the PR. Can we close this issue also?
Also when do you think you can release to chartmuseum so that they're available via helm repo?

**Comment by salaboy** [comment]
@pocorschi that is released already to helm.zeebe.io if you update you should get the latest version. I am closing this issue as well.
